version: '3.9'
services:
  postgresql:
    container_name: postgresql
    build:
      dockerfile: postgresdocker
    image: postgres
    restart: always
    environment:
     - POSTGRES_DB=edem_db
     - POSTGRES_USER=postgres1
     - POSTGRES_PASSWORD=postgres1
    volumes:
      - my-postgres-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/edem_db
      - SPRING_DATASOURCE_USERNAME=postgres1
      - SPRING_DATASOURCE_PASSWORD=postgres1
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

volumes:
   my-postgres-volume: {}