CREATE TABLE person(
                       id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       login varchar(150) NOT NULL unique,
                       password varchar NOT NULL,
                       createdAt timestamp,
                       last_login timestamp,
                       username varchar
);
CREATE TABLE message (
                         id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                         receiver_id int REFERENCES person(id) ON DELETE CASCADE,
                         sender_id int REFERENCES person(id) ON DELETE CASCADE,
                         receiver_login VARCHAR REFERENCES person(login) ON DELETE CASCADE,
                         sender_login VARCHAR REFERENCES person(login) ON DELETE CASCADE,
                         message_text VARCHAR,
                         title VARCHAR,
                         is_in_bin int
);
CREATE TABLE file(
                     id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                     message_id int REFERENCES message(id) ON DELETE CASCADE,
                     filename varchar
);
create table avatars(
                        id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        avatar_name varchar NOT NULL,
                        person_id int UNIQUE REFERENCES person(id) ON DELETE CASCADE
)